INFO 2024-05-21 02:27:28,796 autoreload 12488 8572Watching for file changes with StatReloader
INFO 2024-05-21 02:27:30,895 views 12488 8360Index page accessed
INFO 2024-05-21 02:27:30,932 basehttp 12488 8360"GET / HTTP/1.1" 200 3223
WARNING 2024-05-21 02:27:31,045 log 12488 8360Not Found: /favicon.ico
WARNING 2024-05-21 02:27:31,046 basehttp 12488 8360"GET /favicon.ico HTTP/1.1" 404 2636
ERROR 2024-05-21 02:27:42,024 log 12488 8360Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 34, in list_orders
    orders_last_week = [x for x in orders if x.date_ordered > datetime.date.today - datetime.timedelta(days=7)]
                                                              ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'builtin_function_or_method' and 'datetime.timedelta'
ERROR 2024-05-21 02:27:42,027 basehttp 12488 8360"GET /list_orders/6/ HTTP/1.1" 500 65452
INFO 2024-05-21 02:28:02,541 autoreload 12488 8572C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:28:03,322 autoreload 10108 9668Watching for file changes with StatReloader
INFO 2024-05-21 02:28:04,922 basehttp 10108 12100"GET /list_orders/6/ HTTP/1.1" 200 320
INFO 2024-05-21 02:29:01,182 autoreload 10108 9668C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:29:01,899 autoreload 5464 7728Watching for file changes with StatReloader
INFO 2024-05-21 02:29:04,041 basehttp 5464 9092"GET /list_orders/6/ HTTP/1.1" 200 562
INFO 2024-05-21 02:31:09,958 autoreload 5464 7728C:\_GB_django\my_dz\myapp\models.py changed, reloading.
INFO 2024-05-21 02:31:10,696 autoreload 14012 11124Watching for file changes with StatReloader
INFO 2024-05-21 02:31:12,489 basehttp 14012 14072"GET /list_orders/6/ HTTP/1.1" 200 492
INFO 2024-05-21 02:33:23,975 autoreload 14012 11124C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:33:24,617 autoreload 10564 12780Watching for file changes with StatReloader
INFO 2024-05-21 02:38:11,950 autoreload 10564 12780C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:38:12,598 autoreload 5512 3716Watching for file changes with StatReloader
INFO 2024-05-21 02:40:34,740 autoreload 5512 3716C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:40:35,407 autoreload 7216 6240Watching for file changes with StatReloader
INFO 2024-05-21 02:41:36,969 autoreload 7216 6240C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:41:37,653 autoreload 13336 8384Watching for file changes with StatReloader
INFO 2024-05-21 02:42:26,527 autoreload 13336 8384C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:42:27,207 autoreload 872 5792Watching for file changes with StatReloader
INFO 2024-05-21 02:42:29,004 basehttp 872 10872"GET /list_orders/6/ HTTP/1.1" 200 639
INFO 2024-05-21 02:45:55,166 autoreload 872 5792C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:45:55,815 autoreload 13744 2168Watching for file changes with StatReloader
INFO 2024-05-21 02:46:33,194 autoreload 13744 2168C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:46:33,950 autoreload 14192 8268Watching for file changes with StatReloader
INFO 2024-05-21 02:48:45,899 autoreload 14192 8268C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:48:46,588 autoreload 5360 11492Watching for file changes with StatReloader
ERROR 2024-05-21 02:50:17,073 log 5360 2496Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 39, in list_orders
    for x in orders_last_week:
TypeError: 'NoneType' object is not iterable
ERROR 2024-05-21 02:50:17,077 basehttp 5360 2496"GET /list_orders/6/ HTTP/1.1" 500 65631
INFO 2024-05-21 02:51:51,433 autoreload 5360 11492C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:51:52,154 autoreload 3200 5464Watching for file changes with StatReloader
INFO 2024-05-21 02:52:01,291 autoreload 3200 5464C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:52:02,023 autoreload 6744 11976Watching for file changes with StatReloader
INFO 2024-05-21 02:52:09,979 autoreload 6744 11976C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:52:10,625 autoreload 10008 6900Watching for file changes with StatReloader
ERROR 2024-05-21 02:52:13,574 log 10008 12088Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 38, in list_orders
    if len(orders_last_week)>0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
ERROR 2024-05-21 02:52:13,577 basehttp 10008 12088"GET /list_orders/6/ HTTP/1.1" 500 65520
INFO 2024-05-21 02:54:21,884 autoreload 10008 6900C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:54:22,584 autoreload 7252 5372Watching for file changes with StatReloader
ERROR 2024-05-21 02:54:26,895 log 7252 14012Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 39, in list_orders
    if len(orders_last_week)>0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
ERROR 2024-05-21 02:54:26,897 basehttp 7252 14012"GET /list_orders/6/ HTTP/1.1" 500 65556
INFO 2024-05-21 02:54:49,785 autoreload 7252 5372C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:54:50,511 autoreload 11760 11984Watching for file changes with StatReloader
INFO 2024-05-21 02:54:52,166 autoreload 11760 11984C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:54:52,836 autoreload 1352 10496Watching for file changes with StatReloader
ERROR 2024-05-21 02:54:54,697 log 1352 4084Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 39, in list_orders
    if len(orders_last_week)>0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
ERROR 2024-05-21 02:54:54,700 basehttp 1352 4084"GET /list_orders/6/ HTTP/1.1" 500 65556
INFO 2024-05-21 02:56:05,229 autoreload 1352 10496C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:56:05,937 autoreload 6564 11148Watching for file changes with StatReloader
ERROR 2024-05-21 02:56:07,135 log 6564 7280Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 39, in list_orders
    if len(orders_last_week)>0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
ERROR 2024-05-21 02:56:07,138 basehttp 6564 7280"GET /list_orders/6/ HTTP/1.1" 500 65544
INFO 2024-05-21 02:57:13,000 autoreload 6564 11148C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:57:13,648 autoreload 10748 13252Watching for file changes with StatReloader
INFO 2024-05-21 02:57:29,993 autoreload 10748 13252C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:57:30,730 autoreload 9784 4596Watching for file changes with StatReloader
ERROR 2024-05-21 02:57:32,315 log 9784 3820Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 39, in list_orders
    if len(orders_last_week)>0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
ERROR 2024-05-21 02:57:32,318 basehttp 9784 3820"GET /list_orders/6/ HTTP/1.1" 500 65545
INFO 2024-05-21 02:57:50,645 autoreload 9784 4596C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:57:51,380 autoreload 2384 12332Watching for file changes with StatReloader
ERROR 2024-05-21 02:57:52,380 log 2384 5192Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 50, in list_orders
    if len(orders_last_month)>0:
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
ERROR 2024-05-21 02:57:52,383 basehttp 2384 5192"GET /list_orders/6/ HTTP/1.1" 500 65916
INFO 2024-05-21 02:59:37,119 autoreload 2384 12332C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:59:37,791 autoreload 7616 10872Watching for file changes with StatReloader
ERROR 2024-05-21 02:59:40,095 log 7616 7920Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 51, in list_orders
    if len(orders_last_month)>0:
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
ERROR 2024-05-21 02:59:40,098 basehttp 7616 7920"GET /list_orders/6/ HTTP/1.1" 500 66101
INFO 2024-05-21 03:02:23,744 autoreload 7616 10872C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:02:24,431 autoreload 9460 3228Watching for file changes with StatReloader
INFO 2024-05-21 03:03:23,823 autoreload 9460 3228C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:03:24,465 autoreload 9404 6224Watching for file changes with StatReloader
INFO 2024-05-21 03:03:33,507 autoreload 9404 6224C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:03:34,168 autoreload 1912 9128Watching for file changes with StatReloader
ERROR 2024-05-21 03:03:36,952 log 1912 13048Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 74, in list_orders
    return render (request, 'myapp/list_orders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 860, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{data_week}' from '{data_week}'
ERROR 2024-05-21 03:03:36,967 basehttp 1912 13048"GET /list_orders/6/ HTTP/1.1" 500 173912
ERROR 2024-05-21 03:04:38,654 log 1912 13048Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'end'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 74, in list_orders
    return render (request, 'myapp/list_orders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'end', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
ERROR 2024-05-21 03:04:38,666 basehttp 1912 13048"GET /list_orders/6/ HTTP/1.1" 500 178578
INFO 2024-05-21 03:06:46,067 basehttp 1912 13048"GET /list_orders/6/ HTTP/1.1" 200 195
INFO 2024-05-21 03:07:33,181 autoreload 1912 9128C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:07:33,911 autoreload 14048 9588Watching for file changes with StatReloader
INFO 2024-05-21 03:07:35,575 autoreload 14048 9588C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:07:36,257 autoreload 9172 14332Watching for file changes with StatReloader
INFO 2024-05-21 03:07:37,938 autoreload 9172 14332C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:07:38,620 autoreload 8892 9224Watching for file changes with StatReloader
INFO 2024-05-21 03:07:42,295 basehttp 8892 14308"GET /list_orders/6/ HTTP/1.1" 200 195
INFO 2024-05-21 03:08:19,376 autoreload 8892 9224C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:08:20,094 autoreload 6396 10340Watching for file changes with StatReloader
INFO 2024-05-21 03:08:21,715 basehttp 6396 10536"GET /list_orders/6/ HTTP/1.1" 200 195
INFO 2024-05-21 03:09:37,833 autoreload 6396 10340C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:09:38,510 autoreload 1924 13764Watching for file changes with StatReloader
INFO 2024-05-21 03:09:43,380 autoreload 1924 13764C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:09:44,069 autoreload 8700 9640Watching for file changes with StatReloader
ERROR 2024-05-21 03:09:46,376 log 8700 9348Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 39, in list_orders
    if order.date_ordered < (datetime.datetime.now() - datetime.timedelta(days=7)):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare datetime.datetime to datetime.date
ERROR 2024-05-21 03:09:46,380 basehttp 8700 9348"GET /list_orders/6/ HTTP/1.1" 500 65796
INFO 2024-05-21 03:10:14,340 autoreload 8700 9640C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:10:15,017 autoreload 3020 11456Watching for file changes with StatReloader
INFO 2024-05-21 03:10:17,685 autoreload 3020 11456C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:10:18,377 autoreload 9136 1660Watching for file changes with StatReloader
INFO 2024-05-21 03:10:20,042 autoreload 9136 1660C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:10:20,729 autoreload 10476 5804Watching for file changes with StatReloader
INFO 2024-05-21 03:10:22,076 basehttp 10476 12212"GET /list_orders/6/ HTTP/1.1" 200 195
INFO 2024-05-21 03:11:47,917 autoreload 10476 5804C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:11:48,609 autoreload 12700 6480Watching for file changes with StatReloader
INFO 2024-05-21 03:11:51,796 basehttp 12700 5192"GET /list_orders/6/ HTTP/1.1" 200 195
INFO 2024-05-21 03:12:25,403 autoreload 12700 6480C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:12:26,076 autoreload 11992 3528Watching for file changes with StatReloader
INFO 2024-05-21 03:12:29,829 autoreload 11992 3528C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:12:30,481 autoreload 11844 12676Watching for file changes with StatReloader
INFO 2024-05-21 03:12:32,556 basehttp 11844 6780"GET /list_orders/6/ HTTP/1.1" 200 1019
INFO 2024-05-21 03:12:58,586 autoreload 11844 12676C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:12:59,256 autoreload 10948 7752Watching for file changes with StatReloader
INFO 2024-05-21 03:13:01,751 basehttp 10948 5108"GET /list_orders/6/ HTTP/1.1" 200 1019
INFO 2024-05-21 03:13:41,187 autoreload 10948 7752C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:13:41,848 autoreload 9636 5068Watching for file changes with StatReloader
INFO 2024-05-21 03:13:45,613 autoreload 9636 5068C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:13:46,302 autoreload 5980 9292Watching for file changes with StatReloader
INFO 2024-05-21 03:13:49,193 basehttp 5980 11196"GET /list_orders/6/ HTTP/1.1" 200 680
INFO 2024-05-21 03:14:51,264 autoreload 5980 9292C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:14:51,993 autoreload 7760 1496Watching for file changes with StatReloader
INFO 2024-05-21 03:15:10,456 autoreload 7760 1496C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:15:11,126 autoreload 11112 2732Watching for file changes with StatReloader
INFO 2024-05-21 03:15:16,010 autoreload 11112 2732C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:15:16,696 autoreload 6140 5192Watching for file changes with StatReloader
INFO 2024-05-21 03:15:18,365 autoreload 6140 5192C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:15:19,072 autoreload 8600 6480Watching for file changes with StatReloader
INFO 2024-05-21 03:16:12,560 basehttp 8600 1208"GET /list_orders/6/ HTTP/1.1" 200 2261
INFO 2024-05-21 03:18:21,748 autoreload 8600 6480C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:18:22,449 autoreload 13308 12868Watching for file changes with StatReloader
INFO 2024-05-21 03:18:24,276 basehttp 13308 9056"GET /list_orders/6/ HTTP/1.1" 200 2261
INFO 2024-05-21 03:18:26,437 basehttp 13308 9056"GET /list_orders/6/ HTTP/1.1" 200 2261
INFO 2024-05-22 09:27:26,664 autoreload 3688 11880Watching for file changes with StatReloader
INFO 2024-05-22 09:30:02,384 autoreload 3928 4020Watching for file changes with StatReloader
INFO 2024-05-22 09:31:03,710 autoreload 5760 1272Watching for file changes with StatReloader
INFO 2024-05-22 09:31:07,518 views 5760 11468Index page accessed
INFO 2024-05-22 09:31:07,537 basehttp 5760 11468"GET / HTTP/1.1" 200 3223
INFO 2024-05-22 09:31:20,370 basehttp 5760 11468"GET /list_orders/6/ HTTP/1.1" 200 2261
INFO 2024-05-22 09:32:09,813 autoreload 5760 1272C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 09:32:10,442 autoreload 12320 15188Watching for file changes with StatReloader
INFO 2024-05-22 09:32:40,559 basehttp 12320 7624"GET /list_orders/6/ HTTP/1.1" 200 2501
INFO 2024-05-22 09:34:02,725 autoreload 12320 15188C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 09:34:03,440 autoreload 13908 13812Watching for file changes with StatReloader
INFO 2024-05-22 09:36:01,662 autoreload 13908 13812C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 09:36:02,348 autoreload 12276 13920Watching for file changes with StatReloader
INFO 2024-05-22 09:37:58,629 basehttp 12276 7536"GET /list_orders/6/ HTTP/1.1" 200 2859
INFO 2024-05-22 09:38:02,823 basehttp 12276 7536"GET /list_orders/56/ HTTP/1.1" 200 223
INFO 2024-05-22 09:38:08,657 basehttp 12276 7536"GET /list_orders/6/ HTTP/1.1" 200 2859
INFO 2024-05-22 09:38:25,067 autoreload 12276 13920C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 09:38:25,745 autoreload 14032 6212Watching for file changes with StatReloader
INFO 2024-05-22 10:09:08,062 autoreload 484 8184Watching for file changes with StatReloader
INFO 2024-05-22 10:09:29,600 autoreload 484 8184C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 10:09:30,243 autoreload 1144 9444Watching for file changes with StatReloader
INFO 2024-05-22 10:09:38,862 views 1144 7016Index page accessed
INFO 2024-05-22 10:09:38,868 basehttp 1144 7016"GET / HTTP/1.1" 200 3223
INFO 2024-05-22 10:09:45,577 basehttp 1144 7016"GET /list_orders/6/ HTTP/1.1" 200 2859
WARNING 2024-05-22 10:09:56,828 log 1144 7016Not Found: /edit_product
WARNING 2024-05-22 10:09:56,829 basehttp 1144 7016"GET /edit_product HTTP/1.1" 404 2639
INFO 2024-05-22 10:10:29,203 autoreload 1144 9444C:\_GB_django\my_dz\myapp\urls.py changed, reloading.
INFO 2024-05-22 10:10:29,907 autoreload 13684 15080Watching for file changes with StatReloader
INFO 2024-05-22 10:10:34,078 basehttp 13684 8468"GET /edit_product HTTP/1.1" 301 0
ERROR 2024-05-22 10:10:34,186 log 13684 13716Internal Server Error: /edit_product/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 96, in edit_product
    return render(request, 'myapp/edit product.html', {'title': 'edit_product',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp/edit product.html
ERROR 2024-05-22 10:10:34,189 basehttp 13684 13716"GET /edit_product/ HTTP/1.1" 500 80525
INFO 2024-05-22 10:11:22,354 autoreload 13684 15080C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 10:11:23,033 autoreload 3376 12180Watching for file changes with StatReloader
INFO 2024-05-22 10:11:27,620 basehttp 3376 12656"GET /edit_product/ HTTP/1.1" 200 1331
INFO 2024-05-22 10:12:03,969 autoreload 3376 12180C:\_GB_django\my_dz\myapp\forms.py changed, reloading.
INFO 2024-05-22 10:12:04,656 autoreload 3760 7896Watching for file changes with StatReloader
INFO 2024-05-22 10:12:22,125 autoreload 3760 7896C:\_GB_django\my_dz\myapp\forms.py changed, reloading.
INFO 2024-05-22 10:12:22,827 autoreload 8520 2820Watching for file changes with StatReloader
INFO 2024-05-22 10:12:57,842 basehttp 8520 904"GET /edit_product/ HTTP/1.1" 200 1333
INFO 2024-05-22 10:13:18,422 autoreload 8520 2820C:\_GB_django\my_dz\myapp\forms.py changed, reloading.
INFO 2024-05-22 10:13:19,132 autoreload 13412 12592Watching for file changes with StatReloader
INFO 2024-05-22 10:13:21,298 basehttp 13412 5704"GET /edit_product/ HTTP/1.1" 200 1333
INFO 2024-05-22 10:13:58,341 basehttp 13412 5704"POST /edit_product/ HTTP/1.1" 200 1431
INFO 2024-05-22 10:28:14,580 autoreload 6832 12772Watching for file changes with StatReloader
INFO 2024-05-22 10:28:19,069 basehttp 6832 6960"GET /edit_product/ HTTP/1.1" 200 1333
ERROR 2024-05-22 10:28:37,527 log 6832 6960Internal Server Error: /edit_product/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: myapp_product.picture

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 80, in edit_product
    product = Product.objects.filter(pk=pk).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1097, in first
    for obj in queryset[:1]:
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: myapp_product.picture
ERROR 2024-05-22 10:28:37,537 basehttp 6832 6960"POST /edit_product/ HTTP/1.1" 500 135709
INFO 2024-05-22 10:32:30,528 autoreload 6832 12772C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 10:32:31,208 autoreload 13336 10124Watching for file changes with StatReloader
INFO 2024-05-22 10:33:40,097 autoreload 13336 10124C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 10:33:40,868 autoreload 7252 2312Watching for file changes with StatReloader
INFO 2024-05-22 10:34:30,880 autoreload 7252 2312C:\_GB_django\my_dz\myapp\forms.py changed, reloading.
INFO 2024-05-22 10:34:31,562 autoreload 12668 4220Watching for file changes with StatReloader
INFO 2024-05-22 10:34:51,090 autoreload 12668 4220C:\_GB_django\my_dz\myapp\forms.py changed, reloading.
INFO 2024-05-22 10:34:51,769 autoreload 6692 2064Watching for file changes with StatReloader
INFO 2024-05-22 10:34:53,446 autoreload 6692 2064C:\_GB_django\my_dz\myapp\forms.py changed, reloading.
INFO 2024-05-22 10:34:54,162 autoreload 7444 8452Watching for file changes with StatReloader
INFO 2024-05-22 10:35:14,788 autoreload 7444 8452C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 10:35:15,449 autoreload 3604 13628Watching for file changes with StatReloader
INFO 2024-05-22 10:35:42,376 autoreload 3604 13628C:\_GB_django\my_dz\myapp\forms.py changed, reloading.
INFO 2024-05-22 10:35:43,063 autoreload 7892 15300Watching for file changes with StatReloader
INFO 2024-05-22 10:36:34,168 autoreload 7892 15300C:\_GB_django\my_dz\myapp\forms.py changed, reloading.
INFO 2024-05-22 10:36:34,863 autoreload 11520 11804Watching for file changes with StatReloader
INFO 2024-05-22 10:38:51,604 autoreload 11520 11804C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 10:38:52,298 autoreload 3560 6656Watching for file changes with StatReloader
INFO 2024-05-22 10:39:06,601 autoreload 3560 6656C:\_GB_django\my_dz\myapp\models.py changed, reloading.
INFO 2024-05-22 10:39:07,295 autoreload 928 9604Watching for file changes with StatReloader
INFO 2024-05-22 10:39:08,939 autoreload 928 9604C:\_GB_django\my_dz\myapp\models.py changed, reloading.
INFO 2024-05-22 10:39:09,600 autoreload 5980 11120Watching for file changes with StatReloader
INFO 2024-05-22 10:48:39,919 autoreload 5980 11120C:\_GB_django\my_dz\myapp\models.py changed, reloading.
INFO 2024-05-22 10:48:40,620 autoreload 3584 4700Watching for file changes with StatReloader
INFO 2024-05-22 10:48:42,260 autoreload 3584 4700C:\_GB_django\my_dz\myapp\models.py changed, reloading.
INFO 2024-05-22 10:48:42,942 autoreload 6276 11492Watching for file changes with StatReloader
INFO 2024-05-22 10:49:19,252 autoreload 6276 11492C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 10:49:19,914 autoreload 2452 13808Watching for file changes with StatReloader
INFO 2024-05-22 10:50:03,558 autoreload 2452 13808C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 10:50:04,184 autoreload 1488 2776Watching for file changes with StatReloader
INFO 2024-05-22 10:50:14,238 autoreload 1488 2776C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 10:50:14,910 autoreload 11004 7672Watching for file changes with StatReloader
INFO 2024-05-22 10:51:42,717 autoreload 11004 7672C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 10:51:43,419 autoreload 10496 13272Watching for file changes with StatReloader
INFO 2024-05-22 10:52:34,531 autoreload 10496 13272C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 10:52:35,233 autoreload 2528 1292Watching for file changes with StatReloader
INFO 2024-05-22 10:53:24,187 autoreload 2528 1292C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 10:53:24,915 autoreload 2596 10352Watching for file changes with StatReloader
INFO 2024-05-22 10:57:07,569 autoreload 4792 14976Watching for file changes with StatReloader
INFO 2024-05-22 10:57:14,499 basehttp 4792 3880"GET /add_product/ HTTP/1.1" 200 1352
INFO 2024-05-22 11:00:02,241 autoreload 4792 14976C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:00:03,492 autoreload 6628 1148Watching for file changes with StatReloader
INFO 2024-05-22 11:00:05,170 basehttp 6628 12616"GET /add_product/ HTTP/1.1" 200 1351
INFO 2024-05-22 11:03:15,530 basehttp 6628 12616"POST /add_product/ HTTP/1.1" 200 1514
INFO 2024-05-22 11:04:06,837 basehttp 6628 12616"POST /add_product/ HTTP/1.1" 200 1514
INFO 2024-05-22 11:05:19,367 autoreload 8544 10216Watching for file changes with StatReloader
INFO 2024-05-22 11:05:23,173 basehttp 8544 15264"GET /add_product/ HTTP/1.1" 200 1351
INFO 2024-05-22 11:06:10,955 basehttp 8544 15264"POST /add_product/ HTTP/1.1" 200 1514
INFO 2024-05-22 11:08:19,033 basehttp 8544 15264"GET /add_product/ HTTP/1.1" 200 1381
INFO 2024-05-22 11:08:44,693 basehttp 8544 15264"POST /add_product/ HTTP/1.1" 200 1470
INFO 2024-05-22 11:10:43,044 autoreload 8544 10216C:\_GB_django\my_dz\myapp\models.py changed, reloading.
INFO 2024-05-22 11:10:43,761 autoreload 9932 5504Watching for file changes with StatReloader
INFO 2024-05-22 11:10:45,451 autoreload 9932 5504C:\_GB_django\my_dz\myapp\models.py changed, reloading.
INFO 2024-05-22 11:10:46,107 autoreload 1992 5996Watching for file changes with StatReloader
INFO 2024-05-22 11:11:23,498 autoreload 1992 5996C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:11:24,155 autoreload 4424 9984Watching for file changes with StatReloader
INFO 2024-05-22 11:17:26,169 autoreload 4424 9984C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:17:26,884 autoreload 2788 1620Watching for file changes with StatReloader
INFO 2024-05-22 11:20:56,968 autoreload 2788 1620C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:20:57,624 autoreload 9344 8752Watching for file changes with StatReloader
INFO 2024-05-22 11:21:06,735 autoreload 9344 8752C:\_GB_django\my_dz\myapp\forms.py changed, reloading.
INFO 2024-05-22 11:21:07,404 autoreload 14696 10548Watching for file changes with StatReloader
INFO 2024-05-22 11:21:30,062 autoreload 14696 10548C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:21:30,722 autoreload 13140 4228Watching for file changes with StatReloader
INFO 2024-05-22 11:21:38,656 autoreload 13140 4228C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:21:39,336 autoreload 11352 11528Watching for file changes with StatReloader
INFO 2024-05-22 11:21:41,018 autoreload 11352 11528C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:21:41,688 autoreload 9188 7736Watching for file changes with StatReloader
INFO 2024-05-22 11:23:50,512 autoreload 9188 7736C:\_GB_django\my_dz\myapp\urls.py changed, reloading.
INFO 2024-05-22 11:23:51,204 autoreload 13436 8304Watching for file changes with StatReloader
INFO 2024-05-22 11:28:43,596 autoreload 13448 10052Watching for file changes with StatReloader
WARNING 2024-05-22 11:28:55,718 log 13448 3716Not Found: /show_product/
WARNING 2024-05-22 11:28:55,719 basehttp 13448 3716"GET /show_product/ HTTP/1.1" 404 3203
INFO 2024-05-22 11:29:00,336 basehttp 13448 3716"GET /show_product/1 HTTP/1.1" 301 0
ERROR 2024-05-22 11:29:00,395 log 13448 15080Internal Server Error: /show_product/1/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: show_product() got an unexpected keyword argument 'pk_user'
ERROR 2024-05-22 11:29:00,397 basehttp 13448 15080"GET /show_product/1/ HTTP/1.1" 500 61285
INFO 2024-05-22 11:29:34,191 autoreload 13448 10052C:\_GB_django\my_dz\myapp\urls.py changed, reloading.
INFO 2024-05-22 11:29:34,903 autoreload 5212 956Watching for file changes with StatReloader
INFO 2024-05-22 11:29:36,786 basehttp 5212 2324"GET /show_product/1/ HTTP/1.1" 200 461
INFO 2024-05-22 11:30:07,323 basehttp 5212 2324"GET /show_product/21/ HTTP/1.1" 200 442
INFO 2024-05-22 11:31:15,126 basehttp 5212 2324"GET /show_product/21/ HTTP/1.1" 200 447
INFO 2024-05-22 11:31:52,207 basehttp 5212 2324"GET /show_product/21/ HTTP/1.1" 200 441
INFO 2024-05-22 11:32:45,176 basehttp 5212 2324"GET /show_product/21/ HTTP/1.1" 200 446
INFO 2024-05-22 11:33:29,761 basehttp 5212 2324"GET /show_product/21/ HTTP/1.1" 200 446
INFO 2024-05-22 11:33:59,084 basehttp 5212 2324"GET /show_product/21/ HTTP/1.1" 200 431
INFO 2024-05-22 11:34:00,895 basehttp 5212 2324"GET /show_product/21/ HTTP/1.1" 200 431
INFO 2024-05-22 11:34:31,689 basehttp 5212 2324"GET /show_product/21/ HTTP/1.1" 200 437
INFO 2024-05-22 11:34:40,977 basehttp 5212 2324"GET /show_product/21/ HTTP/1.1" 200 437
INFO 2024-05-22 11:34:42,324 basehttp 5212 2324"GET /show_product/21/ HTTP/1.1" 200 437
INFO 2024-05-22 11:34:43,243 basehttp 5212 2324"GET /show_product/21/ HTTP/1.1" 200 437
INFO 2024-05-22 11:35:46,831 autoreload 6468 11752Watching for file changes with StatReloader
INFO 2024-05-22 11:35:50,557 basehttp 6468 7148"GET /show_product/21/ HTTP/1.1" 200 446
INFO 2024-05-22 11:35:51,956 basehttp 6468 7148"GET /show_product/21/ HTTP/1.1" 200 446
INFO 2024-05-22 11:35:53,030 basehttp 6468 7148"GET /show_product/21/ HTTP/1.1" 200 446
INFO 2024-05-22 11:35:53,607 basehttp 6468 7148"GET /show_product/21/ HTTP/1.1" 200 446
INFO 2024-05-22 11:39:03,422 autoreload 6468 11752C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:39:04,110 autoreload 7172 11560Watching for file changes with StatReloader
INFO 2024-05-22 11:39:05,746 autoreload 7172 11560C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:39:06,430 autoreload 11276 14512Watching for file changes with StatReloader
INFO 2024-05-22 11:39:17,427 basehttp 11276 8140"GET /add_product/ HTTP/1.1" 200 1381
ERROR 2024-05-22 11:39:40,846 log 11276 8140Internal Server Error: /add_product/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 134, in add_product
    product = Product(name = name,description = description,price = price,amount = amount,date = date,image = image.path)
                                                                                                              ^^^^^^^^^^
AttributeError: 'InMemoryUploadedFile' object has no attribute 'path'
ERROR 2024-05-22 11:39:40,849 basehttp 11276 8140"POST /add_product/ HTTP/1.1" 500 68695
INFO 2024-05-22 11:42:05,128 autoreload 11276 14512C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:42:05,871 autoreload 11120 10984Watching for file changes with StatReloader
ERROR 2024-05-22 11:42:15,682 log 11120 15260Internal Server Error: /show_product/21/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 82, in show_product
    'path_image': settings.MEDIA_ROOT + product.image }
                  ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'
ERROR 2024-05-22 11:42:15,685 basehttp 11120 15260"GET /show_product/21/ HTTP/1.1" 500 65453
INFO 2024-05-22 11:43:00,645 autoreload 11120 10984C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:43:01,340 autoreload 8852 11632Watching for file changes with StatReloader
INFO 2024-05-22 11:44:43,867 autoreload 8852 11632C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:44:44,588 autoreload 10680 3192Watching for file changes with StatReloader
INFO 2024-05-22 11:45:07,201 autoreload 10680 3192C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:45:07,799 autoreload 12900 15348Watching for file changes with StatReloader
ERROR 2024-05-22 11:45:08,424 log 12900 4800Internal Server Error: /show_product/21/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 83, in show_product
    'path_image': settings.MEDIA_ROOT + product.image }
                  ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'
ERROR 2024-05-22 11:45:08,427 basehttp 12900 4800"GET /show_product/21/ HTTP/1.1" 500 65590
INFO 2024-05-22 11:46:24,181 autoreload 12900 15348C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:46:24,871 autoreload 6152 12800Watching for file changes with StatReloader
INFO 2024-05-22 11:46:27,250 basehttp 6152 1096"GET /show_product/21/ HTTP/1.1" 200 472
INFO 2024-05-22 11:46:57,815 basehttp 6152 1096"GET /show_product/21/ HTTP/1.1" 200 457
INFO 2024-05-22 11:47:49,276 basehttp 6152 1096"GET /show_product/21/ HTTP/1.1" 200 457
INFO 2024-05-22 11:50:06,581 autoreload 6152 12800C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:50:07,260 autoreload 6840 15108Watching for file changes with StatReloader
INFO 2024-05-22 11:50:27,817 autoreload 6840 15108C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:50:28,478 autoreload 6568 13960Watching for file changes with StatReloader
INFO 2024-05-22 11:50:30,126 autoreload 6568 13960C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:50:30,863 autoreload 3764 14952Watching for file changes with StatReloader
INFO 2024-05-22 11:50:32,081 basehttp 3764 13344"GET /show_product/21/ HTTP/1.1" 200 457
INFO 2024-05-22 11:53:42,909 autoreload 3764 14952C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:53:43,583 autoreload 7464 10548Watching for file changes with StatReloader
INFO 2024-05-22 11:54:10,349 autoreload 7464 10548C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:54:11,030 autoreload 7432 8272Watching for file changes with StatReloader
INFO 2024-05-22 11:54:22,167 autoreload 7432 8272C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:54:22,856 autoreload 10032 3464Watching for file changes with StatReloader
INFO 2024-05-22 11:55:09,835 autoreload 10032 3464C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:55:10,565 autoreload 3484 768Watching for file changes with StatReloader
INFO 2024-05-22 11:55:11,694 basehttp 3484 4840"GET /show_product/21/ HTTP/1.1" 200 446
WARNING 2024-05-22 11:55:11,730 log 3484 4840Not Found: /media/bike.png
WARNING 2024-05-22 11:55:11,731 basehttp 3484 4840"GET /media/bike.png HTTP/1.1" 404 3201
INFO 2024-05-22 11:55:14,811 basehttp 3484 4840"GET /show_product/21/ HTTP/1.1" 200 446
WARNING 2024-05-22 11:55:14,839 log 3484 4840Not Found: /media/bike.png
WARNING 2024-05-22 11:55:14,840 basehttp 3484 4840"GET /media/bike.png HTTP/1.1" 404 3201
INFO 2024-05-22 11:56:32,338 autoreload 3484 768C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:56:33,037 autoreload 6324 12880Watching for file changes with StatReloader
INFO 2024-05-22 11:57:19,939 autoreload 6324 12880C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:57:20,626 autoreload 8816 6296Watching for file changes with StatReloader
INFO 2024-05-22 11:58:45,318 autoreload 8816 6296C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 11:58:46,007 autoreload 7616 13888Watching for file changes with StatReloader
INFO 2024-05-22 12:00:12,902 autoreload 7616 13888C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 12:00:13,577 autoreload 14872 8140Watching for file changes with StatReloader
INFO 2024-05-22 12:00:24,658 autoreload 14872 8140C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 12:00:25,306 autoreload 13384 8936Watching for file changes with StatReloader
INFO 2024-05-22 12:00:35,226 basehttp 13384 5472"GET /show_product/21/ HTTP/1.1" 200 439
WARNING 2024-05-22 12:00:35,269 log 13384 5472Not Found: /media//bike.png
WARNING 2024-05-22 12:00:35,270 basehttp 13384 5472"GET /media//bike.png HTTP/1.1" 404 3204
INFO 2024-05-22 12:01:20,176 autoreload 13384 8936C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 12:01:20,896 autoreload 10576 12468Watching for file changes with StatReloader
ERROR 2024-05-22 12:01:22,258 log 10576 1652Internal Server Error: /show_product/21/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 85, in show_product
    'path_image': MEDIA_ROOT + '/' + product.image }
                  ~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'
ERROR 2024-05-22 12:01:22,261 basehttp 10576 1652"GET /show_product/21/ HTTP/1.1" 500 65566
INFO 2024-05-22 12:01:59,512 autoreload 10576 12468C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 12:02:00,219 autoreload 13408 7204Watching for file changes with StatReloader
INFO 2024-05-22 12:02:01,922 autoreload 13408 7204C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 12:02:02,620 autoreload 6168 8052Watching for file changes with StatReloader
INFO 2024-05-22 12:02:03,644 basehttp 6168 10352"GET /show_product/21/ HTTP/1.1" 200 457
INFO 2024-05-22 12:02:54,916 autoreload 6168 8052C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 12:02:55,606 autoreload 12624 9316Watching for file changes with StatReloader
INFO 2024-05-22 12:03:04,616 autoreload 12624 9316C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 12:03:05,286 autoreload 6916 6524Watching for file changes with StatReloader
INFO 2024-05-22 12:03:06,952 autoreload 6916 6524C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 12:03:07,624 autoreload 4216 12972Watching for file changes with StatReloader
INFO 2024-05-22 12:03:27,121 autoreload 4216 12972C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 12:03:27,787 autoreload 8084 10424Watching for file changes with StatReloader
INFO 2024-05-22 12:03:29,471 autoreload 8084 10424C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-22 12:03:30,175 autoreload 1296 9032Watching for file changes with StatReloader
INFO 2024-05-22 12:03:33,608 basehttp 1296 12164"GET /show_product/21/ HTTP/1.1" 200 457
INFO 2024-05-22 12:09:15,998 autoreload 1296 9032C:\_GB_django\my_dz\myapp\models.py changed, reloading.
INFO 2024-05-22 12:09:16,665 autoreload 14740 10208Watching for file changes with StatReloader
INFO 2024-05-22 12:09:19,090 autoreload 14740 10208C:\_GB_django\my_dz\myapp\models.py changed, reloading.
INFO 2024-05-22 12:09:19,730 autoreload 2644 2604Watching for file changes with StatReloader
INFO 2024-05-22 12:12:16,123 autoreload 14644 13700Watching for file changes with StatReloader
INFO 2024-05-22 12:12:18,922 views 14644 7188Index page accessed
INFO 2024-05-22 12:12:18,933 basehttp 14644 7188"GET / HTTP/1.1" 200 3223
INFO 2024-05-22 12:13:43,940 basehttp 14644 7188"GET /list_orders/2/ HTTP/1.1" 200 5760
INFO 2024-05-22 12:14:32,022 basehttp 14644 7188"GET /show_product/21/ HTTP/1.1" 200 468
WARNING 2024-05-22 12:17:40,964 log 14644 7188Not Found: /edit_product/1
WARNING 2024-05-22 12:17:40,965 basehttp 14644 7188"GET /edit_product/1 HTTP/1.1" 404 3201
INFO 2024-05-22 12:17:46,185 basehttp 14644 7188"GET /edit_product/ HTTP/1.1" 200 1508
INFO 2024-05-22 12:18:21,859 basehttp 14644 7188"POST /edit_product/ HTTP/1.1" 200 1613
INFO 2024-05-22 12:19:03,549 basehttp 14644 7188"GET /add_product/ HTTP/1.1" 200 1381
INFO 2024-05-22 12:19:29,091 basehttp 14644 7188"POST /add_product/ HTTP/1.1" 200 1465
INFO 2024-05-22 12:20:27,590 autoreload 6040 3588Watching for file changes with StatReloader
INFO 2024-05-22 12:20:30,796 basehttp 6040 14840"GET /show_product/51 HTTP/1.1" 301 0
INFO 2024-05-22 12:20:30,814 basehttp 6040 10016"GET /show_product/51/ HTTP/1.1" 200 456
